packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@embedded-postgres/linux-x64"
  - "@embedded-postgres/windows-x64"
  - "@node-rs/argon2"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma

allowBuilds:
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/windows-x64': true
  '@node-rs/argon2': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
